services:
  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - "5672:5672"
    env_file:
      - stack.env
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 3
    volumes:
      - ./.rabbitmq:/var/lib/rabbitmq

  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - stack.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - ./.pgdata:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    env_file:
      - stack.env

    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
            - .git/
            - .idea/

        - action: rebuild
          path: ./uv.lock
    depends_on:
      db:
          condition: service_healthy
          restart: true
      rabbitmq:
          condition: service_healthy
          restart: true

  app-worker:
    build: .
    command: uv run -- celery -A otterball_nfl.tasks worker --loglevel=INFO
    restart: unless-stopped
    env_file:
      - stack.env

    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
            - .git/
            - .idea/

        - action: rebuild
          path: ./uv.lock
    depends_on:
      db:
        condition: service_healthy
        restart: true
      rabbitmq:
        condition: service_healthy
        restart: true

  app-scheduler:
    build: .
    command: uv run -- celery -A otterball_nfl.tasks beat --loglevel=INFO
    restart: unless-stopped
    env_file:
      - stack.env

    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
            - .git/
            - .idea/

        - action: rebuild
          path: ./uv.lock
    depends_on:
      db:
        condition: service_healthy
        restart: true
      rabbitmq:
        condition: service_healthy
        restart: true