"""Add finished field to game

Revision ID: 307f2ece47bf
Revises: 43af3a107837
Create Date: 2025-08-31 17:18:47.083662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '307f2ece47bf'
down_revision: Union[str, Sequence[str], None] = '43af3a107837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('finished', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'finished')
    # ### end Alembic commands ###
