"""add state_message

Revision ID: 34efbfea1c58
Revises: d9dbb8a6f9e6
Create Date: 2025-10-03 19:47:39.091036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34efbfea1c58'
down_revision: Union[str, Sequence[str], None] = 'd9dbb8a6f9e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_message',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('UNKNOWN', 'STARTING_SOON', 'IN_PROGRESS', 'RESULT_POSTED', name='statemessagestate'), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('state_message')
    # ### end Alembic commands ###
