"""Added GameTypeScaling

Revision ID: 4edce0cfd4e3
Revises: 24f1ba3e76b5
Create Date: 2025-09-02 15:56:51.647281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4edce0cfd4e3'
down_revision: Union[str, Sequence[str], None] = '24f1ba3e76b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE outcome AS ENUM ('NOT_FINISHED', 'HOME', 'AWAY', 'TIE')")
    op.create_table('gametype_scaling',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('gametype_id', sa.String(), nullable=False),
    sa.Column('factor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['gametype_id'], ['gametype.id'], ),
    sa.PrimaryKeyConstraint('channel_id', 'gametype_id')
    )
    op.execute("""
               ALTER TABLE bet
               ALTER
               COLUMN choice TYPE outcome
        USING CASE
            WHEN choice = 'HOME' THEN 'HOME'::outcome
            WHEN choice = 'AWAY' THEN 'AWAY'::outcome
            WHEN choice = 'TIE' THEN 'TIE'::outcome
            ELSE 'NOT_FINISHED'::outcome
               END
               """)
    op.add_column('game', sa.Column('outcome', sa.Enum('NOT_FINISHED', 'HOME', 'AWAY', 'TIE', name='outcome'), nullable=False, server_default='NOT_FINISHED'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'outcome')
    op.alter_column('bet', 'choice',
               existing_type=sa.Enum('NOT_FINISHED', 'HOME', 'AWAY', 'TIE', name='outcome'),
               type_=postgresql.ENUM('HOME', 'AWAY', 'TIE', name='betchoices'),
               existing_nullable=False)
    op.execute("DROP TYPE outcome")
    op.drop_table('gametype_scaling')
    # ### end Alembic commands ###
