"""added unique constraint for poll

Revision ID: 65c45ad6a85f
Revises: 9036f1e65882
Create Date: 2025-09-05 01:44:02.324803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65c45ad6a85f'
down_revision: Union[str, Sequence[str], None] = '9036f1e65882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_poll_channel_game', 'poll', ['channel_id', 'game_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_poll_channel_game', 'poll', type_='unique')
    # ### end Alembic commands ###
