"""added channel active field

Revision ID: 9036f1e65882
Revises: ad7a8657f8f0
Create Date: 2025-09-04 23:37:45.704348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9036f1e65882'
down_revision: Union[str, Sequence[str], None] = 'ad7a8657f8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('active', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'active')
    # ### end Alembic commands ###
