"""added unique constraint for bet

Revision ID: c3627a65071c
Revises: 65c45ad6a85f
Create Date: 2025-09-05 12:23:09.959877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3627a65071c'
down_revision: Union[str, Sequence[str], None] = '65c45ad6a85f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_bet_user_game_channel', 'bet', ['user_id', 'game_id', 'channel_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_bet_user_game_channel', 'bet', type_='unique')
    # ### end Alembic commands ###
