"""add team color

Revision ID: e95a2f0b6ada
Revises: c3627a65071c
Create Date: 2025-09-05 17:35:33.474469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e95a2f0b6ada'
down_revision: Union[str, Sequence[str], None] = 'c3627a65071c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'color')
    # ### end Alembic commands ###
