"""add GameIdentifier

Revision ID: 55deb0580219
Revises: f656453a42e9
Create Date: 2025-10-15 00:24:14.924194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql.named_types as pg_types
from migrations.utils import check_enum_exists


# revision identifiers, used by Alembic.
revision: str = '55deb0580219'
down_revision: Union[str, Sequence[str], None] = 'f656453a42e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_identifier',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('source', pg_types.ENUM('NFL_DATA_PY', 'ESPN_V2', name='apisource', create_type=not check_enum_exists(op, 'apisource')), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_game_source_external_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_identifier')
    # ### end Alembic commands ###
