"""add emoji_str to team

Revision ID: 5cdb4906ed58
Revises: 62aa3d809f4b
Create Date: 2025-10-13 17:33:04.106330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cdb4906ed58'
down_revision: Union[str, Sequence[str], None] = '62aa3d809f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('emoji_str', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'emoji_str')
    # ### end Alembic commands ###
