"""move state_message_id to poll

Revision ID: 62aa3d809f4b
Revises: 34efbfea1c58
Create Date: 2025-10-04 21:03:08.438600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62aa3d809f4b'
down_revision: Union[str, Sequence[str], None] = '34efbfea1c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll', sa.Column('state_message_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'poll', 'state_message', ['state_message_id'], ['id'])
    op.drop_constraint(op.f('state_message_poll_id_fkey'), 'state_message', type_='foreignkey')
    op.drop_column('state_message', 'poll_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('state_message', sa.Column('poll_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('state_message_poll_id_fkey'), 'state_message', 'poll', ['poll_id'], ['id'])
    op.drop_constraint(None, 'poll', type_='foreignkey')
    op.drop_column('poll', 'state_message_id')
    # ### end Alembic commands ###
