"""added stuff

Revision ID: ad7a8657f8f0
Revises: 2bc54429e7f9
Create Date: 2025-09-03 17:49:49.940724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad7a8657f8f0'
down_revision: Union[str, Sequence[str], None] = '2bc54429e7f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poll', 'message_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poll', 'message_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
