"""add leaderboard_msg_id

Revision ID: d9dbb8a6f9e6
Revises: 2fe4f2e9aa1c
Create Date: 2025-09-16 23:08:25.213821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9dbb8a6f9e6'
down_revision: Union[str, Sequence[str], None] = '2fe4f2e9aa1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('leaderboard_msg_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'leaderboard_msg_id')
    # ### end Alembic commands ###
