"""change TeamIdentifier uq name

Revision ID: e545c69bfb00
Revises: 55deb0580219
Create Date: 2025-10-15 00:25:18.038994

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql.named_types as pg_types
from migrations.utils import check_enum_exists


# revision identifiers, used by Alembic.
revision: str = "e545c69bfb00"
down_revision: Union[str, Sequence[str], None] = "55deb0580219"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_source_external_id"), "team_identifier", type_="unique")
    op.create_unique_constraint(
        "uq_team_source_external_id", "team_identifier", ["source", "external_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_team_source_external_id", "team_identifier", type_="unique")
    op.create_unique_constraint(
        op.f("uq_source_external_id"),
        "team_identifier",
        ["source", "external_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
