"""add ApiSource

Revision ID: f656453a42e9
Revises: 5cdb4906ed58
Create Date: 2025-10-14 16:07:34.737245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f656453a42e9'
down_revision: Union[str, Sequence[str], None] = '5cdb4906ed58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_identifier',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('NFL_DATA_PY', 'ESPN_V2', name='apisource'), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_source_external_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_identifier')
    # ### end Alembic commands ###
